
package smsservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SMSService", targetNamespace = "com.shasteel.erp.sms", wsdlLocation = "http://10.88.0.73:8080/sms/service/smsService?wsdl")
public class SMSService
    extends Service
{

    private final static URL SMSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SMSSERVICE_EXCEPTION;
    private final static QName SMSSERVICE_QNAME = new QName("com.shasteel.erp.sms", "SMSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.88.0.73:8080/sms/service/smsService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SMSSERVICE_WSDL_LOCATION = url;
        SMSSERVICE_EXCEPTION = e;
    }

    public SMSService() {
        super(__getWsdlLocation(), SMSSERVICE_QNAME);
    }

    public SMSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SMSSERVICE_QNAME, features);
    }

    public SMSService(URL wsdlLocation) {
        super(wsdlLocation, SMSSERVICE_QNAME);
    }

    public SMSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SMSSERVICE_QNAME, features);
    }

    public SMSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SMSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ISMS
     */
    @WebEndpoint(name = "SMSImplPort")
    public ISMS getSMSImplPort() {
        return super.getPort(new QName("com.shasteel.erp.sms", "SMSImplPort"), ISMS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISMS
     */
    @WebEndpoint(name = "SMSImplPort")
    public ISMS getSMSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("com.shasteel.erp.sms", "SMSImplPort"), ISMS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SMSSERVICE_EXCEPTION!= null) {
            throw SMSSERVICE_EXCEPTION;
        }
        return SMSSERVICE_WSDL_LOCATION;
    }

}
