package com.xyc.userc.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_role
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Role implements Serializable
{

    private static final long serialVersionUID = 1L;

    /**
     * id
     */
    private int id;

    /**
     * 角色名称
     * role_name
     */
    private String roleName;

    /**
     * 角色编码
     * role_name
     */
    private String roleCode;


    /**
     * 1：已删除 0：未删除
     * is_deleted
     */
    private int isDeleted;

    /**
     * 创建时间
     * gmt_create
     */
    private Date gmtCreate;

    /**
     * 修改时间
     * gmt_modified
     */
    private Date gmtModified;

    /**
     * 父角色id
     * parent_role_id
     */
    private int parentRoleId;

    public Role(int id, String roleName, String roleCode, int isDeleted, Date gmtCreate, Date gmtModified, int parentRoleId)
    {
        this.id = id;
        this.roleName = roleName;
        this.roleCode = roleCode;
        this.isDeleted = isDeleted;
        this.gmtCreate = gmtCreate;
        this.gmtModified = gmtModified;
        this.parentRoleId = parentRoleId;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getRoleName() {
        return roleName;
    }

    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }


    public int getIsDeleted() {
        return isDeleted;
    }

    public void setIsDeleted(int isDeleted) {
        this.isDeleted = isDeleted;
    }

    public Date getGmtCreate() {
        return gmtCreate;
    }

    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    public Date getGmtModified() {
        return gmtModified;
    }

    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    public String getRoleCode() {
        return roleCode;
    }

    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode;
    }

    public int getParentRoleId() {
        return parentRoleId;
    }

    public void setParentRoleId(int parentRoleId) {
        this.parentRoleId = parentRoleId;
    }
}