package com.xyc.userc.entity;

import com.avei.shriety.wx_sdk.pojo.Userinfo;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.List;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_user
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class User extends Userinfo implements Serializable
{
    private static final long serialVersionUID = 1L;



    private String mobilePhone;



    private List<Role> roles;

    public User(String openId, String nickName, String sex, String province, String city, String country,
                String headImgUrl, String privilege, String unionId,String mobilePhone, List<Role> roles)
    {
        this.setOpenid(openId);
        this.setNickname(nickName);
        this.setSex(sex);
        this.setProvince(province);
        this.setCity(city);
        this.setCountry(country);
        this.setHeadimgurl(headImgUrl);
        this.setPrivilege(privilege);
        this.setUnionid(unionId);
        this.mobilePhone = mobilePhone;
        this.roles = roles;
    }

    public List<Role> getRoles() {
        return roles;
    }

    public void setRoles(List<Role> roles) {
        this.roles = roles;
    }


    public String getMobilePhone() {
        return mobilePhone;
    }

    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }

//    @Override
//    public Collection<? extends GrantedAuthority> getAuthorities()
//    {
//        List<SimpleGrantedAuthority> authorities = new ArrayList<>(roles.size());
//        for (Role role : roles)
//        {
//            authorities.add(new SimpleGrantedAuthority(String.valueOf(role.getId())));
//        }
//        return authorities;
//    }
//
//    @Override
//    public String getPassword() {
//        return this.getOpenid();
//    }
//
//    @Override
//    public String getUsername() {
//        return this.getNickname();
//    }
//
//    @Override
//    public boolean isAccountNonExpired() {
//        return true;
//    }
//
//    @Override
//    public boolean isAccountNonLocked()
//    {
//        return true;
//    }
//
//    @Override
//    public boolean isCredentialsNonExpired() {
//        return true;
//    }
//
//    @Override
//    public boolean isEnabled()
//    {
//
//        return true;
//    }
}